language: 
  node_js
node_js:
  "node"
install:
  npm install --only-production
script:
  npm run prod-build
deploy:
  provider: pages
  skip_cleanup: true # keep files after build
  github-token: $GITHUB_TOKEN
  local-dir: dist
  target-branch: master
  on:
    branch: rc